# Generated by Django 4.0 on 2021-12-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_user_bio_remove_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='Professional', max_length=20),
        ),
    ]
